version: '3'

services:
  web:
    ports:
      - 8082:3000
    image: docker.tangerie.xyz/voxcartes:latest
    networks:
      - default
    deploy:
      replicas: 1

networks:
  app:
    driver: overlay