version: '3'

services:
  web:
    ports:
      - 8082:3000
    image: docker.tangerie.xyz/voxcartes:latest
    restart: always
    networks:
      - default
    deploy:
      mode: global

networks:
  app:
    driver: overlay