name: Docker Image CI

env:
  IMAGE_NAME: voxcartes
  ARCH_LIST: linux/arm64/v8,linux/amd64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, media]
    name: Build and push docker image to swarm
    env:
      CURRENT_TAG: ${{ github.sha }}
    steps:
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: docker.tangerie.xyz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print data
        run: echo Building to "latest" and ${{env.CURRENT_TAG}}

      - name: Build and push image
        run: docker buildx build --push --platform ${{env.ARCH_LIST}} -t docker.tangerie.xyz/${{env.IMAGE_NAME}}:latest -t docker.tangerie.xyz/${{env.IMAGE_NAME}}:${{env.CURRENT_TAG}} .

      - name: Run image
        run: docker stack deploy -c docker-compose.yml ${{env.IMAGE_NAME}}